server:
  port: 8080

spring:
  liquibase:
    change-log: classpath:/db/changelog/master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/appcrud
    username: root
    password:
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  main:
    web-application-type: servlet